lb-sync:
  image: founder/rancher-lb-sync:latest # or your own image
  environment:
    LOADBALANCER_STACK_NAME: # the name of the stack which has your loadbalancer
    LOADBALANCER_SERVICE_NAME: # the of the loadbalancer service
  labels:
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
